In [2]:
import numpy as np

In [3]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

In [11]:
# Solution
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3

print("iris_2d shape: {}, volume shape: {}".format(iris_2d.shape, volume.shape))

# Introduce new dimension to match iris_2d's
volume = volume[:, np.newaxis]

print(volume.shape)

# Add the new column
out = np.hstack([iris_2d, volume])

print(out.shape)

iris_2d shape: (150, 5), volume shape: (150,)
(150, 1)
(150, 6)


In [8]:
out[:4]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004]], dtype=object)

In [15]:
# Input
np.random.seed(100)
a = np.random.uniform(1,50, 6)

# Solution:
print(a)
print(a.argsort())
#> [18 7 3 10 15]

# Solution 2:
np.argpartition(-a, 5)[:5]
#> [15 10  3  7 18]

# Below methods will get you the values.
# Method 1:
a[a.argsort()][-5:]

# Method 2:
np.sort(a)[-5:]

# Method 3:
np.partition(a, kth=-5)[-5:]

# Method 4:
a[np.argpartition(-a, 5)][:5]

[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692]
[4 5 1 2 0 3]


array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  6.95688692])

In [3]:
x = np.array([[3, 1, 2], [5, 4, 6]])
print("x:{}".format(x))
sorted_x_idx = np.argsort(x)
print("sorted_x_idx: {}".format(sorted_x_idx))
print("shape: {}".format(sorted_x_idx.shape))
y1 = x[0][sorted_x_idx[0]]
y2 = x[1][sorted_x_idx[1]]
y = np.vstack((y1, y2))
print("y: {}".format(y))
col1 = x[:, 0]
col2 = x[:, 1]
col3 = x[:, 2]
print("col1: {}, shape: {}".format(col1, col1.shape))
print(col2)
print(col3)
col1_max = np.maximum(4, col1)
print(col1_max)

x:[[3 1 2]
 [5 4 6]]
sorted_x_idx: [[1 2 0]
 [1 0 2]]
shape: (2, 3)
y: [[1 2 3]
 [4 5 6]]
col1: [3 5], shape: (2,)
[1 4]
[2 6]
[4 5]


In [4]:
X = np.array([1, 2, 3])
for data in X:
    print(data)

1
2
3


In [5]:
np.squeeze(X)

array([1, 2, 3])